dbt_gcp:
  target: dev
  outputs: 
    dev:
      type: bigquery
      method: service-account
      project: gcpzoomcamp
      location: asia-east1
      dataset: trips_data_all
      threads: 4
      keyfile: /media/groot/_projects1/dbt_gcp/.secrets/key-sa.json

# this is needed for dbt build to check proper location
default:
  target: default
  outputs: 
    default:
      type: bigquery
      method: service-account
      project: gcpzoomcamp
      location: asia-east1
      dataset: trips_data_all
      threads: 4
      keyfile: /media/groot/_projects1/dbt_gcp/.secrets/key-sa.json
